# -*- coding: utf-8 -*-
"""PrimeNumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umRHdwHyMUuXCxNQ-XhIxSkytSMqwdtb

***Program for displaying all prime numbers in a range***
"""

def prime(a, b):
  for num in range(a, b):
    if all(num%i !=0 for i in range(2,num)):
     print(num)

if __name__ == "__main__":
    a = int(input("Enter lower range"))
    b = int(input("Enter upper range"))
    prime(a, b)