# -*- coding: utf-8 -*-
"""ListReversal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umRHdwHyMUuXCxNQ-XhIxSkytSMqwdtb

***PRINT LIST IN REVERSE ORDER***
"""

def rev(l):
  return l[::-1]

if __name__ == "__main__":
  list = input("Enter the list")
  print(rev(list))